name: 'Auto Release Draft'
description: 'Drafts a GitHub release with the changes introduced'
author: 'Tim Chartrand'

# Add your action's branding here. This will appear on the GitHub Marketplace.
branding:
  icon: 'heart'
  color: 'red'

# Define your inputs here.
# inputs:
#   milliseconds:
#     description: 'Your input description here'
#     required: true
#     default: '1000'

# Define your outputs here.
outputs:
  release-url:
    description: 'The URL of the GH release that was drafted'

runs:
  using: node20
  main: dist/index.js
