name: Test
on:
  push:
    branches:
      - main
  
jobs:
  test:
    name: Test
    runs-on: windows-latest
    steps:
      - name: Get the sources
        uses: actions/checkout@v4
      - name: Restore the dependencies
        run: npm ci
      - name: Create a release draft for a version tag
        id: create-release-draft
        uses: ./
      - name: Print Hello
        run: echo Hello!
      - name: Print Nothing
        run: echo 
      - name: Print the URL of the release draft
        run: echo ${{ steps.create-release-draft.output.release-url }}

